name: DoubleJump
main: space.wolv.doublejump.DoubleJump
version: v0.2
authors: [wolvfang]
commands:
  doublejump:
    description: main command for DoubleJump
    permission: doublejump.reload
    usage: /doublejump
  toggledoublejump:
    description: toggle command for doublejump
    permission: doublejump.toggle
    usage: /toggledoublejump
    aliases: [/tdj]
